name: latexmk
on:
  push:
jobs:
  latexmk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y python3-pygments && sudo pip3 install pygments
      - run: sudo apt-get -y install ghostscript
      - uses: yegor256/latexmk-action@0.11.1
        with:
          path: paper
          opts: -pdf
          packages: acmart cjk ffcode href-ul datetime fmtcount libertine paralist makecell footmisc currfile enumitem wrapfig lastpage biblatex titling svg trimspaces catchfile transparent textpos fvextra xstring framed environ totpages hyperxmp ifmtarg ncctools comment anyfontsize fdsymbol algpseudocodex algorithmicx stmaryrd preprint cyrillic cm-super lh to-be-determined cancel iexec docshots upquote eolang crumbs clicks ppt-slides fontsize changepage ifoddpage doi pgf tikzfill pdfcol listingsutf8 bbold semantic cleveref adjustbox mdframed zref needspace csquotes bibcop debate
      - run: |
          mkdir gh-pages
          cp paper/article.pdf gh-pages
      - uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
        if: github.ref == 'refs/heads/master'
